### ISSUE TITLE
SO Charts not working in java 8 

### ISSUE THREAD

**Issue by mailtokarthik2003** [syampillai/SOCharts#1]
I am using java 8 for my project so i run vaadin 14 project with SO Charts got error java version problem. i am not able to update my java because all of my project will be collapsed give me some idea....

**Comment by syampillai** [comment]
This add-on requires Java 11+.

Switching from 8 to 11 should be straight forward (switching to 9 or 10 is not recommended though). I don't think you will have any compatibility issues.

Actually, updating up to Java 15 is not at all a problem. However, if you want to switch to Java 16, you need to take care of few issues.
