### ISSUE TITLE
The formatter of the tooltip does not work.

### ISSUE THREAD

**Issue by combineads** [syampillai/SOCharts#10]
I'd like to print out the tooltip as follows.
```
  tooltip: {
    trigger: 'item',
    formatter: '{a} <br/>{b} : {c} ({d}%)'
  },
```

It was developed as follows, but the formatter does not work and is printed literally.
```
        defaultTooltip.apply {
          type = Tooltip.Type.Item
          append("{a} <br/>{b} : {c} ({d}%)")
        }
```

<img width="212" alt="image" src="https://user-images.githubusercontent.com/3220939/207873659-e20dfef1-ab3a-4e81-95b5-a1af4169af3c.png">

Or I need to add percentage in tooltip.

Thank you.

**Comment by syampillai** [comment]
tooltip.append(String) add the literal string to the tooltip. That's why you are getting the output like that.
You can look at the tooltip example in the [EXAMPLES](https://storedobject.com/examples/?login=AUTO) - Search with the keyword "tooltip".

**Comment by combineads** [comment]
Thank you. I understand.
