### ISSUE TITLE
Invalid import warning since updating to Vaadin 23.3

### ISSUE THREAD

**Issue by p-engl** [syampillai/SOCharts#12]
We receive the following warnings in the console at server startup since updating to Vaadin 23.3 (and using Vite):

2023-01-11 16:31:30,433 ERROR: com.vaadin.flow.server.frontend.TaskUpdateImports - Invalid import 'lit'
import {property, customElement} from 'lit/decorators.js' in file xyz
2023-01-11 16:31:30,435 ERROR: com.vaadin.flow.server.frontend.TaskUpdateImports - Invalid import 'echarts/dist/echarts.min'
export class SOChart extends LitElement {

    static get properties() {
        return {
            minw: { type: String },
            maxw: { type: String },
            minh: { type: String },
            maxh: { type: String },
            width: { type: String },
            height: { type: String }
        ' in file xyz

It seems like thie file chart.js is missing a semi colon on line 1 and 3.

**Comment by syampillai** [comment]
This issue is fixed in the latest version.
Thanks for reporting.
