### ISSUE TITLE
Support the horizontal-only zoom 

### ISSUE THREAD

**Issue by vilmosnagy** [syampillai/SOCharts#13]
See this chart: https://echarts.apache.org/examples/en/editor.html?c=area-time-axis

I cannot zoom on the vertical axis, only on the horizontal one.

As far as I understand this is the JS descriptor for it:

```javascript
  toolbox: {
    feature: {
      dataZoom: {
        yAxisIndex: 'none'
      },
      restore: {},
      saveAsImage: {}
    }
  },
```

**Comment by vilmosnagy** [comment]
Do you have any suggestion how to implement this? If you could give me a general direction I'm willing to submit a PR in the next weeks.

**Comment by syampillai** [comment]
This is implemented and is available in the latest version.
Please have a look at the API for Toolbox.Zoom class.

**Comment by vilmosnagy** [comment]
Thanks, I've found it <3
