### ISSUE TITLE
Missing resize handling

### ISSUE THREAD

**Issue by norbertroamsys** [syampillai/SOCharts#24]
Not sure whether this is a bug, missing feature or wrong usage...

We use `SOChart` for generating a line chart using the following code:

```
    private Component createChart(final Map<LocalDateTime, BigDecimal> powerMap) {
        final SOChart soChart = new SOChart();

        // fill in data values
        final TimeData xValues = new TimeData();
        final Data yValues = new Data();
        powerMap.entrySet().forEach(entry -> {
            xValues.add(entry.getKey());
            yValues.add(DecimalValues.divideByInt(entry.getValue(), 1000));
        });

        xValues.setName("Uhrzeit");
        yValues.setName("Werte");

        final LineChart lineChart = new LineChart(xValues, yValues);
        lineChart.setName(getTranslation("Leistung (AC)");
        lineChart.setColors(new Color(255, 193, 37));
        lineChart.setSmoothness(true);
        lineChart.getAreaStyle(true).setColor(new Color(255, 193, 37));
        lineChart.getPointSymbol(true).setType(PointSymbolType.ROUND_RECTANGLE);

        final XAxis xAxis = new XAxis(DataType.TIME);
        xAxis.setMinAsMinData();

        final YAxis yAxisLeft = new YAxis(DataType.NUMBER);
        yAxisLeft.setName("kW");
        yAxisLeft.setNameLocation(Location.MIDDLE);
        yAxisLeft.setNameRotation(90);
        yAxisLeft.setNameGap(35);
        yAxisLeft.setMin(0);
        yAxisLeft.setMaxAsMaxData();

        final RectangularCoordinate rc = new RectangularCoordinate(xAxis, yAxisLeft);
        lineChart.plotOn(rc);

        soChart.add(lineChart);
        return soChart;
    } 
```
The created chart is inserted into a `VerticalLayout` as last component (see screenshot).
This `VerticalLayout` panel is switched to different height and width by media queries in CSS. 
Our problem is that the chart (div, canvas) does not resize dependent to its parent. 
I have provided a screenshot to demonstrate the effect and also show part of the DOM.

We noticed that this behavior is different in the [ECharts Demo](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWszGAG0iAXMmuhgE4QDmFApqYQOQCGAHhAM70A0x6L7ACsAjQwtQqhIkwATxDUGbABaMAJsADuXHrAC-xHd3TZqNaCvHaVjMI0IBtegBlq7MAFdoFWAAoAggGEASnoAXUMpUAYAI2AwTABbLXQDYkgwYwtJYwAzMAYcsCSpamY82HoACWo3USL0Njco0VKGAAYAFgA6WF8QcmxYACZWwYBmIpTiZl9WNkypWXlygGNrE2BSaTrYKxt7elaANnxW1q5y44BGAFYuemPRs84L_Hbb8MlJA4B2E6fy343O6_R7nei_N7bT7lVoADj-YPhQM49HhoOeqNe7200IOAE4ERiCcj6AT0eUCZCPtDypdWoTafSSXT8OT6CyqTjPuzLgyefhmby2ZdeZyaSR2YM-ZcpcypcKpWLxbTRtLVczVcLVUrxez2tL9cz9cL9TqaezrtLLczLcLLWbcZdjqcwU6Be92Q9_p6sVDuZdfi6MQH3XcQ8KIdjlbT4UGY6GUZc0d6k77qY6CXH2cSPZcySnKe9YFyvsM-WWSWW2WWqbAwiWSHw2I5GFFqNhxLBhKJSAA3Rgd2DfXT6bjEaQzdj2bQST4yOQMfvYNzUP3QRjxJb0ADWAHU_fFhIRWunYPEWIQRSeud3aEvL9foevN45gKtIDAGMtqCJaNsUpIs6SPOW5Liua4blue4APR7iAB5HrArSdI-nznswl6dJcp63n2A7Hlhp7PtQr7vlA0Bfj-Pb_sQ9b1LQEDUHMsB2DOXLEfgTguGw7ieD4ATBKeuy2CxJ5Ic8YmodGQydNczyjLA8mycW0noJwcmwIczzfM8sKnjSOmwHizx4rJzx0vp0KXKMzzDLZ9kNp8kkSS5jmSHRc6LPkwirqebDxFgYCKIQYCkCup7LDgGwMKQFBRN4gzXBpeY2bAozfIJXKMKQ1CMAAyjIGREOKkXYNF5SxfFiXJXiqXpcEXJ6JIAF1twOgANxAA) for the same chart type: As you can see the chart is resized to its parent container properly.

Is there a way to do this in SOChart? We noticed that width and height is set maybe by the frontend JS code for the nested divs and the canvas element. 

Please note that we are currently using so-charts version 2.3.0 because of a dependency to Java 11.
But as far as I see there is also no support in version 3.2.1

Thanks for your feedback and support!

![chart-resize-problem](https://github.com/syampillai/SOCharts/assets/3448010/c853bad7-86a5-4ed9-b4a6-79d39e39efc3)

**Comment by norbertroamsys** [comment]
In the meantime we investigated in some workaround to get the resizing working.
What we found out:
* The div-Container in witch the `SOChart` should be inserted has to have width="100%" and height="100%"
* The `SOChart` itself should also set to width/height/minWidth/minHeight/maxWidth/maxHeight of 100%

Following this rules it seems that the initial size is fine then.

But the dynamic resizing does not work: The chart does not change it's size if the parent container gets a new size.
We implemented a **BrowserResizeEventHandler** as a workaround. To force the resizing on event we toggle the percentage between 100% to 99.9%. 

All this workaround code is encapsulated in an Helper called `ChartResizer`:

```
import com.storedobject.chart.SOChart;
import com.vaadin.flow.shared.Registration;
import java.util.Objects;

/**
 * Helper for forcing (re)sizing after create and on browser window resize events.
 *
 * @author nbecker
 */
public class ChartResizer {

    private static final String FULL_SIZE = "100%";

    private final SOChart chart;
    private Registration resizeRegistration;

    /**
     * Wraps the chart for resize handling.
     *
     * @param chart the chart
     */
    public static void wrap(final SOChart chart) {
        new ChartResizer(chart);
    }

    private ChartResizer(final SOChart chart) {
        this.chart = chart;

        setSize(FULL_SIZE);
        chart.addAttachListener(event -> {
           resizeRegistration = event.getUI().getPage().addBrowserWindowResizeListener(resizeEvent -> adjustSize());
        });
        chart.addDetachListener(event -> {
            if (resizeRegistration != null) {
                resizeRegistration.remove();
                resizeRegistration = null;
            }
        });
    }

    private void adjustSize() {
        if (Objects.equals(chart.getHeight(), FULL_SIZE)) {
            // set a different value to force resizing
            setSize("99.9%");
        } else {
            setSize(FULL_SIZE);
        }
    }

    private void setSize(final String size) {
        chart.setWidth(size);
        chart.setHeight(size);
        chart.setMinWidth(size);
        chart.setMinHeight(size);
        chart.setMaxWidth(size);
        chart.setMaxHeight(size);
    }

}
```

 A call to `ChartResizer.wrap(myChart)` will initially resize the chart and install the event handler.

We hope this information is useful for you to find a much better solution.
Maybe one option can be to make the [EChart.resize()](https://echarts.apache.org/en/api.html#echartsInstance.resize) function accessible via the `SOChart` server wrapper?

**Comment by norbertroamsys** [comment]
It seems that this issue is resolved in https://github.com/syampillai/SOCharts/pull/9.
So our problem is that we have to use version 2.3.0 by now (because of Java 11).
@syampillai : I this is the case you can close this issue of cause.

**Comment by syampillai** [comment]
Yes, this was resolved in an earlier release.
