### ISSUE TITLE
Geomap with marked points

### ISSUE THREAD

**Issue by janaleis** [syampillai/SOCharts#29]
I would like to create a geomap with marked points on specific coordinates. 
e.g https://echarts.apache.org/examples/en/editor.html?c=map-polygon
 
As a workaround I tried to put a scatter chart in front of an svg but this isn't really helpful for my use-case.
 
Is there a way to do it or will there be any more features for geomaps?

**Comment by syampillai** [comment]
Geomaps are currently not supported.
It may be supported in the future but I can't provide a timeline for that now.
