### ISSUE TITLE
Enabling "aria.enable" to generate aria-label for accessibility

### ISSUE THREAD

**Issue by hazren-sulaiman** [syampillai/SOCharts#30]
Hi, is there a way to enable "aria.enable" in order to generate "aria-label" for accessibility? This will be useful for screenreader to describe the chart.

Reference: https://echarts.apache.org/handbook/en/best-practices/aria/

**Comment by syampillai** [comment]
This is not supported currently.
However, you can append additional JSON to the generated output via new `addCustomEncoding` methods added recently in version 3.2.5.
```
        SOChart soChart = new SOChart() {
            @Override
            protected void addCustomEncoding(ComponentPart componentPart, StringBuilder buffer) {
                if(componentPart == null) {
                    buffer.append("""
                            "aria": {
                                "show": true
                              },
                            """);
                }
            }
        };

```
