### ISSUE TITLE
PieChart Custom ToolTip

### ISSUE THREAD

**Issue by thejoker101** [syampillai/SOCharts#32]
Is there a way to do a custom tooltip for a pie chart? There's an example for a LineChart, but applying that to a PieChart doesn't actually render anything. Doing `.append(dataValues)` in the custom tooltip will show the value, but if you do a custom AbstractDataProvider, it just seems to come up blank.

**Comment by syampillai** [comment]
Due to a bug, it had the `AbstractDataProvider` to the SOChart instance in order to make it work.
However, this issue is already resolved in the latest version 3.2.5
