### ISSUE TITLE
How to update chart when data is updated dynamically?

### ISSUE THREAD

**Issue by panderior** [syampillai/SOCharts#33]
I was unable to update or redraw the chart when the data I used was updated. I obtain a stream of data at different times from a message broker and I wanted to display that in real-time. I could not find methods to achieve this task.
Could you point me to the right direction?

**Comment by syampillai** [comment]
[Data Pushing Example](https://storedobject.com/examples/?login=AUTO)

Search for: Data Push

**Comment by panderior** [comment]
It is what I was looking for. Thank you for your support.
