### ISSUE TITLE
 Reference to Data is ambiguous

### ISSUE THREAD

**Issue by mgrecuccio** [syampillai/SOCharts#36]
When instantiating the class com.storedobject.chart.Data like Data data = new Data(25d, 40d, 20d, 30d); I get the following error:

reference to Data is ambiguous
[ERROR]   both constructor Data(java.lang.Number...) in com.storedobject.chart.Data and constructor Data(double...) in com.storedobject.chart.Data match

**Comment by cedricopfermann** [comment]
Hi,
I'm getting the same issue using new Data().

**Comment by syampillai** [comment]
Are you not using version 3.2.5?
I am not getting this issue.

**Comment by cedricopfermann** [comment]
Yes, latest version, on Java 21 and eclipse.

**Comment by syampillai** [comment]
For some strange reason, my IDE (IntelliJ IDEA) was not showing any errors!!
I have made the necessary changes and released a new version.

**Comment by cedricopfermann** [comment]
Everything is fine now.
Thank for your quick fix !!

**Comment by syampillai** [comment]
Issue was resolved.
